
name: pyinstaller build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Windows Build
      uses: eric2788/pyinstaller-build@0.1.3
      with:
        main: main
        python_version: 3.11.1
        artifact: windows-build
        use-dependencies: true
        no-console: true

    - uses: actions/upload-artifact@v2
      with:
        name: linux-build
        path: dist/windows-build
